#!/bin/sh

setxkbmap dvorak &
mpd &
transmission-daemon &
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources &
redshift -P -O 3500 &
fcitx -d &
dunst &
transmission-rss -f &
sb-mpdup &
polybar bar
