#!/bin/sh

/usr/bin/prime-offload
bspc rule -r "*"
bspc monitor -d 1 2 3 4 5 6 7 8 9 H
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action3 resize_corner
bspc config click_to_focus none
bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# ---------------------------------
bspc config border_width         2
bspc config window_gap          12

# autostart
pulseaudio --start
mpd
setxkbmap dvorak &
pgrep -x sxhkd > /dev/null || sxhkd &
# sxhkd &
sb-musicup &
# transmission-daemon &
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources &
fcitx -d &
dunst &
# transmission-rss -f &
launch-polybar &
# polybar bar &
redshift -l 5:100 -t 4000:3000 -r  &
xwallpaper --zoom ~/.local/share/wallpaper.jpg &
picom -b &
mute yes mic &
mute no mon &
twoeyes &
pgrep bs-swallow || bs-swallow &
# bs-swallow &
shortcuts &
remaps &
discover-overlay &
