#!/bin/sh


setxkbmap dvorak

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 H

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# autostart
mpd &
transmission-daemon &
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources &
redshift -P -O 3500 &
fcitx -d &
dunst &
transmission-rss -f &
polybar bar &
redshift -l 5:100 -t 3500:2000 -r  &
xwallpaper --zoom ~/.local/share/wallpaper.jpg &
picom -b &
mute yes mic &
mute no mon &
sb-mpdup &
twoeyes
